### ISSUE TITLE
Why not Flutter?

### ISSUE THREAD

**Issue by ZQDesigned** [HFUTHole/HFUTHoleApp#14]
It may be a better choice if you choose Flutter(a cross-platform framework based on Programming language Dart). It's used by some international companies and products, such as Tencent(for example, QQ Music), Bilibili App and Bilibili Comics App. This App uses React Native as a cross-platform framework but it has a low performance on some Android phone(they may use low-performance SOCs). Flutter uses declarative UI(similar with Jetpack Compose, also a cross-platform UI library based on Kotlin and use Kotlin's cross-platform compiler to implement cross-platform capabilities) to create user interface, and thanks to Dart's JIT compiler, the development process is also greatly simplified, reducing costs and increasing efficiency. Thanks for taking time to read my issue.

**Comment by ZQDesigned** [comment]
@SnowingFox @yixiaojiu @quartz68 @Prixii

**Comment by SnowingFox** [comment]
因为上手flutter需要学习Dart，以及Dart社区，这也是一个很大的成本，react native几乎兼容react所有用法以及npm包，所以和正常开发web react没什么区别，除了UI组件库其他的都能正常使用，方便上手开发

还有一个原因是flutter开发需要在本地启一个模拟器，而rn搭配expo则只需要扫码就行，方便真机调试

**Comment by ZQDesigned** [comment]
> 因为上手flutter需要学习Dart，以及Dart社区，这也是一个很大的成本，react native几乎兼容react所有用法以及npm包，所以和正常开发web react没什么区别，除了UI组件库其他的都能正常使用，方便上手开发
> 
> 还有一个原因是flutter开发需要在本地启一个模拟器，而rn搭配expo则只需要扫码就行，方便真机调试

Flutter 似乎不需要在本地开模拟器？我都是通过真机调试的，iOS和安卓端均是如此。本人对前端技术掌握并不是很熟练，所以技术选型可能不会考虑与前端方向相关的技术。感谢解答！

**Comment by yixiaojiu** [comment]
> It may be a better choice if you choose Flutter(a cross-platform framework based on Programming language Dart). It's used by some international companies and products, such as Tencent(for example, QQ Music), Bilibili App and Bilibili Comics App. This App uses React Native as a cross-platform framework but it has a low performance on some Android phone(they may use low-performance SOCs). Flutter uses declarative UI(similar with Jetpack Compose, also a cross-platform UI library based on Kotlin and use Kotlin's cross-platform compiler to implement cross-platform capabilities) to create user interface, and thanks to Dart's JIT compiler, the development process is also greatly simplified, reducing costs and increasing efficiency. Thanks for taking time to read my issue.

React Native 也意识到了自己的性能问题，已经推出新的架构，可以等待 Expo 未来的更新。

**Comment by Prixii** [comment]
> > 因为上手flutter需要学习Dart，以及Dart社区，这也是一个很大的成本，react native几乎兼容react所有用法以及npm包，所以和正常开发web react没什么区别，除了UI组件库其他的都能正常使用，方便上手开发
> > 还有一个原因是flutter开发需要在本地启一个模拟器，而rn搭配expo则只需要扫码就行，方便真机调试
> 
> Flutter 似乎不需要在本地开模拟器？我都是通过真机调试的，iOS和安卓端均是如此。本人对前端技术掌握并不是很熟练，所以技术选型可能不会考虑与前端方向相关的技术。感谢解答！

（虽然我也更喜欢Flutter），但是Flutter有一个问题是，调试iOS似乎不得不使用Mac，目前手头上并没有Mac，而且按照现在app的完成度，沉没成本有点大了

**Comment by ZQDesigned** [comment]
是这样的，绝大多数跨平台App开发，想要测试苹果客户端都需要有Mac，一开始没有太多了解React Native，后来才知道他可以直接用expo go来进行调试，会给开发者节省下不小的开支（不过还是有一些情况必须要Mac，比如针对iOS平台的适配）。因为自己前端方向的技术很次，所有没学RN，Vue（uniapp）一类的技术，不过问题不大，现在学还来得及


------------------ Original ------------------
From: PriXII ***@***.***&gt;
Date: Wed,Oct 4,2023 10:18 AM
To: HFUTHole/HFUTHoleApp ***@***.***&gt;
Cc: ZQDesigned ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [HFUTHole/HFUTHoleApp] Why not Flutter? (Issue #14)





   
因为上手flutter需要学习Dart，以及Dart社区，这也是一个很大的成本，react native几乎兼容react所有用法以及npm包，所以和正常开发web react没什么区别，除了UI组件库其他的都能正常使用，方便上手开发
 还有一个原因是flutter开发需要在本地启一个模拟器，而rn搭配expo则只需要扫码就行，方便真机调试
  
Flutter 似乎不需要在本地开模拟器？我都是通过真机调试的，iOS和安卓端均是如此。本人对前端技术掌握并不是很熟练，所以技术选型可能不会考虑与前端方向相关的技术。感谢解答！
  
（虽然我也更喜欢Flutter），但是Flutter有一个问题是，调试iOS似乎不得不使用Mac，目前手头上并没有Mac，而且按照现在app的完成度，沉没成本有点大了
